import Head from 'next/head'
import  Home  from '../components/Home'
import fetch from 'isomorphic-fetch'
import '../node_modules/bootstrap/dist/css/bootstrap.min.css'
import style from '../styles/home.module.css'

function HomePage({users, tasks}) {

//  console.log( tasks );
// console.log( users );
  return (
  <div className={style.background}>
    <Head>
      <title>Client app</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
  </Head>

    <main className='container' >
        <Home users={users} tasks={tasks}  /> 
    </main>
  </div>
  ) 
}


HomePage.getInitialProps = async () => {
  const response = await fetch('http://localhost:3001/people')
  const resp = await  fetch('http://localhost:3001/tasks')
  const taskData = await resp.json();
   const data = await response.json();
   return { users: data, tasks: taskData }
}






export default HomePage